In [5]:
import pandas as pd

In [11]:
results_fiw_v3 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_fiw_v3.csv")
results_fiw_v4 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_fiw_v4.csv")
results_thws_v3 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_thws_v3.csv")
results_thws_v4 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_thws_v4.csv")
results_fiw_v4_gemini_mix_DC10_KG3 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_fiw_v4_gemini_mix_DC10_KG3.csv")
results_fiw_v4_gemini_naive_DC10 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_fiw_v4_gemini_naive_DC10.csv")

## FIW

In [9]:
results_fiw_v3[:100].describe()

,genauigkeit,F1,BLEU,factual_correctness,semantic_similarity
count,100.000000,100.000000,100.000000,100.00000,100.000000
mean,0.500000,0.142539,0.074839,0.28800,0.491217
std,0.502519,0.125276,0.157636,0.29532,0.140733
min,0.000000,0.000000,0.000000,0.00000,0.206292
25%,0.000000,0.056902,0.016533,0.00000,0.386433
50%,0.500000,0.107387,0.028428,0.25000,0.480128
75%,1.000000,0.219829,0.054067,0.50000,0.591745
max,1.000000,0.727273,1.000000,1.00000,0.867627

In [8]:
results_fiw_v4[:100].describe()

,genauigkeit,F1,BLEU,factual_correctness,semantic_similarity
count,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.540000,0.129402,0.054455,0.286700,0.476461
std,0.500908,0.128362,0.121733,0.309101,0.137688
min,0.000000,0.000000,0.000000,0.000000,0.179942
25%,0.000000,0.036782,0.011461,0.000000,0.375049
50%,1.000000,0.098124,0.021930,0.235000,0.469017
75%,1.000000,0.178788,0.036768,0.562500,0.537388
max,1.000000,0.727273,1.000000,1.000000,0.862269

In [7]:
results_fiw_v4_gemini_mix_DC10_KG3.describe()

,genauigkeit,F1,BLEU,factual_correctness,semantic_similarity,duration_seconds
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.660000,0.141153,0.060913,0.297500,0.485434,5.324300
std,0.476095,0.108707,0.134816,0.314001,0.138609,1.123183
min,0.000000,0.000000,0.000000,0.000000,0.156054,3.840000
25%,0.000000,0.058943,0.010643,0.000000,0.379395,4.617500
50%,1.000000,0.120644,0.019284,0.235000,0.465793,5.035000
75%,1.000000,0.193020,0.048353,0.512500,0.589782,5.812500
max,1.000000,0.585366,1.000000,1.000000,0.857961,10.670000

In [12]:
results_fiw_v4_gemini_naive_DC10.describe()

,genauigkeit,F1,BLEU,factual_correctness,semantic_similarity,duration_seconds
count,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000
mean,0.470000,0.108031,0.056921,0.21500,0.460151,2.575200
std,0.501614,0.107288,0.129295,0.29414,0.142106,1.037403
min,0.000000,0.000000,0.000000,0.00000,0.168549,1.700000
25%,0.000000,0.000000,0.015757,0.00000,0.362358,2.007500
50%,0.000000,0.083333,0.026187,0.00000,0.441870,2.250000
75%,1.000000,0.158421,0.030891,0.38500,0.536797,2.760000
max,1.000000,0.458333,1.000000,1.00000,0.847975,9.830000

In [10]:
print(results_fiw_v4_gemini_mix_DC10_KG3[results_fiw_v4_gemini_mix_DC10_KG3["factual_correctness"]==1].count())

question               3
bot_answer             3
gold_answer            3
genauigkeit            3
F1                     3
BLEU                   3
factual_correctness    3
semantic_similarity    3
duration_seconds       3
dtype: int64

## THWS

In [8]:
results_thws_v3.describe()

,genauigkeit,F1,BLEU,factual_correctness,semantic_similarity
count,99.000000,99.000000,99.000000,99.000000,99.000000
mean,0.353535,0.058460,0.028565,0.121414,0.312258
std,0.480500,0.077740,0.035924,0.257535,0.185975
min,0.000000,0.000000,0.000000,0.000000,-0.056712
25%,0.000000,0.000000,0.004638,0.000000,0.193855
50%,0.000000,0.033898,0.024342,0.000000,0.326517
75%,1.000000,0.101019,0.033969,0.060000,0.428571
max,1.000000,0.377778,0.204480,1.000000,0.825582

In [9]:
results_thws_v4.describe()

,genauigkeit,F1,BLEU,factual_correctness,semantic_similarity
count,99.000000,99.000000,99.000000,99.000000,99.000000
mean,0.595960,0.110326,0.069425,0.266364,0.399912
std,0.493203,0.139038,0.136171,0.320607,0.241326
min,0.000000,0.000000,0.000000,0.000000,0.034809
25%,0.000000,0.000000,0.002261,0.000000,0.227721
50%,1.000000,0.082474,0.017902,0.170000,0.421486
75%,1.000000,0.140394,0.048573,0.490000,0.588707
max,1.000000,0.677419,0.617651,1.000000,0.922372

In [4]:
df1 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_2025-08-28_15-00-39_fiw_v4_1.csv")
df2 = pd.read_csv("/Users/lelange/Uni/askTHWS/test_results/results_2025-08-29_11-05-55_fiw_v4_2.csv")

In [5]:
df = pd.concat([df1, df2], ignore_index=True)

In [6]:
display(df.head())

,question,bot_answer,gold_answer,genauigkeit,F1,BLEU,factual_correctness,semantic_similarity
0,Welche Studiengänge bietet die THWS aktuell an?,Die THWS bietet eine Kombination aus Theorie u...,Aktuell bietet die THWS folgende Studiengänge ...,0,0.068182,0.004063,0.22,0.344099
1,Gibt es eine Zulassungsbeschränkung für den St...,Für die Zulassung in zulassungsbeschränkten Ba...,"Nein, der Studiengang Wirtschaftsinformatik is...",0,0.022989,0.015733,0.00,0.537714
2,Wie lange dauert das Studium der Wirtschaftsin...,Ich konnte keine passenden Informationen zu Ih...,Das Vollzeitstudium Wirtschaftsinformatik daue...,0,0.000000,0.000000,0.00,0.331199
3,In welcher Sprache wird der Studiengang Wirtsc...,Der Studiengang Wirtschaftsingenieurwesen und ...,Der Studiengang Wirtschaftsinformatik wird hau...,0,0.196721,0.019768,0.00,0.636489
4,Wie viele ECTS-Punkte müssen im Studium Wirtsc...,Um frühestens mit der Bearbeitung der Bachelor...,Es müssen insgesamt 210 ECTS-Punkte erworben w...,0,0.145455,0.007215,0.00,0.524941

In [8]:
df.to_csv("results_fiw_v4.csv", index=False)